spring:
  application:
    name: surge-auth
  profiles:
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      server-addr: ${SC_NACOS_ADDRESS}
      username: ${SC_NACOS_USERNAME}
      password: ${SC_NACOS_PASSWORD}
      discovery:
        group: ${SC_NACOS_GROUP}
        namespace: ${SC_NACOS_NAMESPACE}
      config:
        group: ${SC_NACOS_GROUP}
        namespace: ${SC_NACOS_NAMESPACE}
  config:
    import:
      - optional:nacos:common-web.yml
      - optional:nacos:${spring.application.name}.yml
